### ISSUE TITLE
Local pre-commit checks pass, but in branch workflow fails

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/template-repo-python#67]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

The recent fix for #65 passes locally in the pre-commit hooks just fine: no trailing whitespace issues.

However, in the `branch_cicd.yaml` workflow—ostensibly running the same code—the trailing whitespace lint fails.

### 🕵️ Expected behavior

I expected these tests to be identical.

### 📜 To Reproduce

Try committing something.

### 🖥 Environment Info

N/A

### 📚 Version of Software Used

N/A

### 🩺 Test Data / Additional context

See https://github.com/NASA-PDS/template-repo-python/actions/runs/4244100107

**Comment by jordanpadams** [comment]
@nutjob4life I am guessing we need a follow-on ticket to push this out to all the python/java repos?

**Comment by nutjob4life** [comment]
@jordanpadams assuming it wasn't just a one-off fluke, yeah. (And just the Python repos. We don't have this kind of linting on Java repos.)

**Comment by jordanpadams** [comment]
@nutjob4life copy that. do we have the git-secrets pre-commit for Java? or no?

**Comment by nutjob4life** [comment]
@jordanpadams negative. The [original ticket](https://github.com/NASA-PDS/template-repo-python/issues/65) for git-secrets was for Python-only.

There's a [separate ticket](https://github.com/NASA-PDS/template-repo-java/issues/25) for Java. It's not yet on the board, so I just added the needed label.
